spring:
  application:
    name: owner-service
  datasource:
    hikari:
      maximum-pool-size: 2
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
message: "hello from github"
server:
  servlet:
    context-path: /owners
  
