server:
  port: 8010
  servlet:
    context-path: /pets
message: Hello from github
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size:  2
